name: Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker tag'
        default: 'github'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pheweb:${{ github.event.inputs.tag }}