name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies and run pre-commit
      run: |
        python3 -m pip install pre-commit
        pre-commit run --all-files

    - name: Test wheel with pytest
      run: |
        python3 -m pip install wheel # for bdist_wheel
        python3 -m pip install pytest
        python3 -m pip freeze
        python3 setup.py sdist bdist_wheel
        sh -c "cd /tmp && python3 -m pip install $PWD/dist/*.whl" # must be in a new dir to avoid finding build artifacts
        python3 -m pip freeze
        sh -c "cd /tmp && pytest $PWD/tests" # must be in a new dir to avoid finding source code
